final products = [
  {
    'id': '0',
    'title': 'Adidas Canvas',
    'price': 44.52,
    'imageUrl': 'assets/images/1.png',
    'company': 'Adidas',
    'sizes': [9, 10, 11, 12,13],
  },
  {
    'id': '1',
    'title': 'High Jordans',
    'price': 20.12,
    'imageUrl': 'assets/images/2.png',
    'company': 'Nike',
    'sizes': [9, 10, 12],
  },
  {
    'id': '2',
    'title': 'Puma Running Shoes',
    'price': 28.95,
    'imageUrl': 'assets/images/3.png',
    'company': 'Puma',
    'sizes': [8, 9, 10],
  },
  {
    'id': '3',
    'title': 'Reebok Light',
    'price': 24.65,
    'imageUrl': 'assets/images/4.png',
    'company': 'Reebok',
    'sizes': [8, 9, 10],
  },
  {
    'id': '4',
    'title': 'Sketchers Rough',
    'price': 39.69,
    'imageUrl': 'assets/images/5.png',
    'company': 'Sketchers',
    'sizes': [8, 9, 10],
  },
];